kind: pipeline
type: kubernetes
name: test

trigger:
  event: [push, pull_request]

steps:
  - name: test
    image: node:18.8-alpine
    commands:
      - npm ci
      - npm run lint
      - npm run test
      - npm run format

---
kind: pipeline
type: kubernetes
name: build

trigger:
  event: [push, pull_request]

_docker_defaults: &docker_defaults
  image: plugins/docker
  settings:
    username: { from_secret: quay_username }
    password: { from_secret: quay_password }
    registry: quay.io
    repo: quay.io/zebbra/zebbra_store
    build_args_from_env:
      - DRONE_COMMIT_SHA
    mtu: 1316

depends_on:
  - test

steps:
  - name: builder
    <<: *docker_defaults
    settings:
      tags: builder
      target: builder
      cache_from:
        - quay.io/zebbra/zebbra_store:builder
      mtu: 1316
  - name: build
    <<: *docker_defaults
    settings:
      custom_labels: [quay.expires-after=4w]
      tags: "git-${DRONE_COMMIT_SHA:0:7},latest"
      cache_from:
        - quay.io/zebbra/zebbra_store:builder
      mtu: 1316
      build_args:
        - VERSION=${DRONE_COMMIT_SHA:0:7}
