kind: pipeline
type: kubernetes
name: build

steps:
  - name: greeting
    image: zebrastore
    settings:
      username: username
      password: password
      registry: quay.io
      repo: tim_zurbuchen/zebbra_store
      file: Dockerfile
