kind: pipeline
type: kubernetes
name: build

steps:
  - name: build
    image: plugins/docker
    settings:
      username: { from_secret: username }
      password: { from_secret: password }
      registry: quay.io
      repo: tim_zurbuchen/zebbra_store
      file: Dockerfile
